# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 15
  timeout: 300
  encoding: utf8
  host: <%= Figaro.env.db_host %>
  database: <%= Figaro.env.db_name %>
  user: <%= Figaro.env.db_user %>
  password: <%= Figaro.env.db_password %>

development:
  <<: *default

test:
  <<: *default
  database: asahi_test

staging:
  <<: *default

production:
  <<: *default
